@extends('admin.layout')

@section('title', 'Kalendář - Rezervace')

@section('content')
<div class="bg-white rounded-lg shadow-md p-6">
    <h2 class="text-2xl font-bold mb-6">Kalendář rezervací</h2>
    
    <div id="calendar" class="grid grid-cols-7 gap-2">
        <!-- Calendar will be generated by JavaScript -->
    </div>
</div>

<script>
const reservations = @json($reservations);

function generateCalendar() {
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth();
    
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    
    const calendar = document.getElementById('calendar');
    calendar.innerHTML = '';
    
    // Header
    const days = ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne'];
    days.forEach(day => {
        const header = document.createElement('div');
        header.className = 'text-center font-bold p-2 bg-gray-100';
        header.textContent = day;
        calendar.appendChild(header);
    });
    
    // Empty cells before first day
    const startDay = firstDay.getDay() === 0 ? 6 : firstDay.getDay() - 1;
    for (let i = 0; i < startDay; i++) {
        calendar.appendChild(document.createElement('div'));
    }
    
    // Days
    for (let day = 1; day <= lastDay.getDate(); day++) {
        const date = new Date(year, month, day);
        const dateStr = date.toISOString().split('T')[0];
        
        const dayCell = document.createElement('div');
        dayCell.className = 'border p-2 min-h-[80px] hover:bg-gray-50';
        dayCell.innerHTML = `<div class="font-semibold">${day}</div>`;
        
        // Collect all reservations for this date
        const dayReservations = [];
        reservations.forEach(res => {
            const from = new Date(res.from);
            from.setHours(0, 0, 0, 0);
            
            const to = new Date(res.to);
            to.setHours(0, 0, 0, 0);
            
            if (date >= from && date <= to) {
                dayReservations.push(res);
            }
        });
        
        // Display all reservations for this day (stacked)
        dayReservations.forEach(res => {
            const statusClass = res.status === 'PENDING' ? 'bg-yellow-200' : 
                               res.status === 'CONFIRMED' ? 'bg-green-200' : 'bg-red-200';
            
            const resDiv = document.createElement('div');
            resDiv.className = `text-xs p-1 mt-1 rounded ${statusClass} cursor-pointer hover:opacity-80`;
            resDiv.textContent = res.name;
            resDiv.onclick = () => viewDetails(res.id);
            dayCell.appendChild(resDiv);
        });
        
        calendar.appendChild(dayCell);
    }
}

generateCalendar();

// Detail modal function
function viewDetails(id) {
    fetch(`/karavan-web/backend/public/admin/reservations/${id}`)
        .then(res => res.json())
        .then(data => {
            const from = new Date(data.from).toLocaleDateString('cs-CZ');
            const to = new Date(data.to).toLocaleDateString('cs-CZ');
            const fromDate = new Date(data.from);
            const toDate = new Date(data.to);
            const days = Math.floor((toDate - fromDate) / (1000 * 60 * 60 * 24)) + 1;
            
            document.getElementById('detailContent').innerHTML = `
                <p><strong>Jméno:</strong> ${data.name}</p>
                <p><strong>Email:</strong> ${data.email}</p>
                <p><strong>Telefon:</strong> ${data.phone}</p>
                <p><strong>Od:</strong> ${from}</p>
                <p><strong>Do:</strong> ${to}</p>
                <p><strong>Počet dní:</strong> ${days}</p>
                <p><strong>Status:</strong> ${data.status}</p>
                <p><strong>Poznámka:</strong></p>
                <div class="bg-gray-50 p-3 rounded" style="white-space: pre-line;">${data.note || 'Žádná poznámka'}</div>
            `;
            document.getElementById('detailModal').classList.remove('hidden');
        });
}

function closeModal() {
    document.getElementById('detailModal').classList.add('hidden');
}
</script>

<!-- Detail Modal -->
<div id="detailModal" class="hidden fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
    <div class="bg-white rounded-lg p-6 max-w-2xl w-full mx-4">
        <div class="flex justify-between items-center mb-4">
            <h3 class="text-xl font-bold">Detail rezervace</h3>
            <button onclick="closeModal()" class="text-gray-500 hover:text-gray-700 text-2xl">&times;</button>
        </div>
        <div id="detailContent" class="space-y-2">
            <!-- Content loaded via JS -->
        </div>
    </div>
</div>
@endsection
